### ISSUE TITLE
Building workflow generates undefined variable errors (aw.IsRunning, aw.RunInBackground, updateAvailable, link)

### ISSUE THREAD

**Issue by tansawit** [nikitavoloboev/alfred-my-mind#25]
When trying to run 
```bash
alfred build
```
on the repo the following errors are generated

```bash
./update.go:19:29: undefined: aw.IsRunning
./update.go:23:9: undefined: aw.RunInBackground
./update.go:40:9: undefined: updateAvailable
./wiki.go:25:14: undefined: link
./wiki.go:31:25: undefined: link
```

From what I understand the first 2 undefines are related to changes to the AwGo library and changing it to wf.IsRunning/wf.RunInBackground seems to do the trick.

For the 'undefined link' they seem to reference the Link struct defined in line 11 of wiki.go. Changing the two references to 'Link' also seems to fix the issue.

However I can't seem to figure out how to fix the 'updateAvailable' error short of removing the entire 'Icon(updateAvailable)' line.

Let me know if I should do a PR for this or if I might be able to help in any way.

**Comment by nikitavoloboev** [comment]
Would love a PR for this. The errors thrown are due to changes in AwGo so code needs to be changed for it to build.
