### ISSUE TITLE
Alfred your mind?

### ISSUE THREAD

**Issue by massens** [nikitavoloboev/alfred-my-mind#5]
Hi Nikita, 

For other people that create their own mindmaps. How difficult would it be to create an **alfred-your-mind** where it would be an interface to their mindmaps created with mindnode?

Thanks!
Marc

**Comment by nikitavoloboev** [comment]
Hey @massens 

Actually it's really simple to do for yourself. Simply make your own workflow and transfer `parser``package.json` `spider.py` and `maps.json` files. And then in `maps.json` you specify the maps you want to parse.

Currently it grabs all URLs from maps and makes Alfred JSON from that that you can open from Alfred similar to how I do it in my workflow.

For updating and downloading the maps I run `bash update.sh` but you have to take care of some dependencies first.

**Comment by nikitavoloboev** [comment]
Did you manage to get it working? 🙂
